"""dr-providers v0.2 kernel: request, response, config, failures.

The stable intersection of four provider-implementation lineages:
request, response, usage, warning, failure record, provider config,
transport. See whetstone-ai ``docs/composable/llm_provider.md``.
"""

from dr_providers.kernel.config import (
    GEMINI_API_KEY_ENV,
    GEMINI_OPENAI_COMPAT_BASE_URL,
    OPENAI_API_KEY_ENV,
    OPENAI_BASE_URL,
    OPENROUTER_API_KEY_ENV,
    OPENROUTER_BASE_URL,
    EndpointKind,
    MessageRole,
    PromptMessage,
    ProviderConfig,
    ProviderKind,
    ReasoningRequestShape,
    RequestControl,
    TokenLimitParameter,
    gemini_chat_config,
    openai_chat_config,
    openai_responses_config,
    openrouter_chat_config,
)
from dr_providers.kernel.conformance import (
    conformance_warnings,
    with_conformance_warnings,
)
from dr_providers.kernel.failures import (
    FAILURE_ERROR_TYPES,
    RECOVERABLE_FAILURE_CLASSES,
    RETRYABLE_FAILURE_CLASSES,
    SANITIZE_KEYS,
    FailureClass,
    PermanentProviderError,
    ProviderFailure,
    ProviderFailureError,
    RateLimitedProviderError,
    ResourceExhaustionProviderError,
    TransientProviderError,
    UnknownProviderError,
    UnsupportedControlError,
    classify_status_code,
    failure_record,
    raise_failure,
    sanitize_kwargs,
)
from dr_providers.kernel.fixture import (
    FixtureOutcome,
    FixtureProvider,
    Provider,
)
from dr_providers.kernel.request import (
    LlmRequest,
    build_payload,
    endpoint_path,
)
from dr_providers.kernel.response import (
    CostInfo,
    LlmResponse,
    LlmWarning,
    TokenUsage,
    WarningSeverity,
    cost_from_body,
    parse_chat_completions_body,
    parse_response,
    parse_responses_body,
    token_usage_from_body,
)
from dr_providers.kernel.transport import (
    HttpProvider,
    TransportPolicy,
)

__all__ = [
    "FAILURE_ERROR_TYPES",
    "GEMINI_API_KEY_ENV",
    "GEMINI_OPENAI_COMPAT_BASE_URL",
    "OPENAI_API_KEY_ENV",
    "OPENAI_BASE_URL",
    "OPENROUTER_API_KEY_ENV",
    "OPENROUTER_BASE_URL",
    "RECOVERABLE_FAILURE_CLASSES",
    "RETRYABLE_FAILURE_CLASSES",
    "SANITIZE_KEYS",
    "CostInfo",
    "EndpointKind",
    "FailureClass",
    "FixtureOutcome",
    "FixtureProvider",
    "HttpProvider",
    "LlmRequest",
    "LlmResponse",
    "LlmWarning",
    "MessageRole",
    "PermanentProviderError",
    "PromptMessage",
    "Provider",
    "ProviderConfig",
    "ProviderFailure",
    "ProviderFailureError",
    "ProviderKind",
    "RateLimitedProviderError",
    "ReasoningRequestShape",
    "RequestControl",
    "ResourceExhaustionProviderError",
    "TokenLimitParameter",
    "TokenUsage",
    "TransientProviderError",
    "TransportPolicy",
    "UnknownProviderError",
    "UnsupportedControlError",
    "WarningSeverity",
    "build_payload",
    "classify_status_code",
    "conformance_warnings",
    "cost_from_body",
    "endpoint_path",
    "failure_record",
    "gemini_chat_config",
    "openai_chat_config",
    "openai_responses_config",
    "openrouter_chat_config",
    "parse_chat_completions_body",
    "parse_response",
    "parse_responses_body",
    "raise_failure",
    "sanitize_kwargs",
    "token_usage_from_body",
    "with_conformance_warnings",
]
