"""Golden identity tests for the Provider Call Definition/Config/Request.

These pin the identity contract the design requires:
  * Definition, Config, and Request are each identified by a full 64-char
    SHA-256 Identity Hash via dr-serialize.
  * Definition identity fully captures its declared variables: route,
    constraints, required controls, and declared extension keys.
  * Config identity embeds the owning Definition Identity Hash plus the
    assigned controls and extensions; transport policy is excluded.
  * Request identity is exactly one Config reference (by hash) + one
    Transcript, with no copied controls and no transport policy.
  * Pinned literal hashes catch drift in the floating dr-serialize
    dependency or in canonicalization.
"""

from __future__ import annotations

import re

import pytest
from dr_serialize import build_identity_document, identity_document_hash
from pydantic import ValidationError

from dr_providers import (
    ApiKeyEnv,
    ControlConstraints,
    ControlValidationError,
    GenerationControls,
    MessageRole,
    ModelRoute,
    PromptMessage,
    Protocol,
    ProviderBaseUrl,
    ProviderBodyExtensions,
    ProviderCallConfig,
    ProviderCallDefinition,
    ProviderCallRequest,
    ProviderKind,
    ProviderTransportPolicy,
    ReasoningEffort,
    RequestControl,
    TokenLimitParameter,
    Transcript,
    openai_chat_config,
    policy_for,
)
from dr_providers.modeling.call import (
    PROVIDER_CALL_CONFIG_SCHEMA,
    PROVIDER_CALL_CONFIG_SCHEMA_VERSION,
    PROVIDER_CALL_DEFINITION_SCHEMA_VERSION,
)

FULL_SHA256 = re.compile(r"^[0-9a-f]{64}$")

TRANSCRIPT = Transcript(
    messages=(PromptMessage(role=MessageRole.USER, content="hi"),)
)


def _fixed_definition() -> ProviderCallDefinition:
    return ProviderCallDefinition(
        definition_id="openai.chat_completions",
        route=ModelRoute(
            provider=ProviderKind.OPENAI,
            protocol=Protocol.CHAT_COMPLETIONS,
            model="m",
        ),
        constraints=ControlConstraints(
            token_limit_parameter=TokenLimitParameter.MAX_COMPLETION_TOKENS,
        ),
        required_controls=frozenset({RequestControl.TOKEN_LIMIT}),
    )


def _fixed_config() -> ProviderCallConfig:
    return _fixed_definition().materialize(
        controls=GenerationControls(token_limit=64)
    )


def _fixed_request() -> ProviderCallRequest:
    return ProviderCallRequest(config=_fixed_config(), transcript=TRANSCRIPT)


# The pinned literals below are generated by ``_print_golden`` at the bottom
# of this module; keep them in sync only through a recorded decision.
GOLDEN_DEFINITION_HASH = (
    "0b6088fd506e6c9e50a030783ae90a135b37cf54de5160f305e865a7cce6e74e"
)
GOLDEN_CONFIG_HASH = (
    "f38e85f9d599ee30468418b31d4a3ddc8337aa77d03e2adf5ad562e3c54d81f7"
)
GOLDEN_REQUEST_HASH = (
    "d10ea5a27db8b402b021fbb2b9c6e03c842e7c3c2fb9914455674315b493fd7d"
)


class TestPinnedGoldenHashes:
    def test_definition_hash_is_pinned(self) -> None:
        assert _fixed_definition().identity_hash == GOLDEN_DEFINITION_HASH

    def test_config_hash_is_pinned(self) -> None:
        assert _fixed_config().identity_hash == GOLDEN_CONFIG_HASH

    def test_request_hash_is_pinned(self) -> None:
        assert _fixed_request().identity_hash == GOLDEN_REQUEST_HASH


class TestDefinitionSchemaVersionOwnership:
    def test_schema_version_exists_only_on_identity_document(self) -> None:
        definition = _fixed_definition()

        assert PROVIDER_CALL_DEFINITION_SCHEMA_VERSION == 2
        assert "schema_version" not in ProviderCallDefinition.model_fields
        properties = ProviderCallDefinition.model_json_schema()["properties"]
        assert "schema_version" not in properties
        assert "schema_version" not in definition.identity_payload()
        assert (
            definition.identity_document().schema_version
            == PROVIDER_CALL_DEFINITION_SCHEMA_VERSION
        )

    def test_explicit_schema_version_is_rejected(self) -> None:
        data = _fixed_definition().model_dump(mode="python")

        with pytest.raises(ValidationError):
            ProviderCallDefinition.model_validate(
                {
                    **data,
                    "schema_version": PROVIDER_CALL_DEFINITION_SCHEMA_VERSION,
                }
            )


class TestHashesAreFullSha256:
    def test_definition_hash_shape(self) -> None:
        assert FULL_SHA256.match(_fixed_definition().identity_hash)

    def test_config_hash_shape(self) -> None:
        assert FULL_SHA256.match(_fixed_config().identity_hash)

    def test_request_hash_shape(self) -> None:
        assert FULL_SHA256.match(_fixed_request().identity_hash)

    def test_config_hash_matches_manual_identity_document(self) -> None:
        config = openai_chat_config(
            model="m", controls=GenerationControls(token_limit=64)
        )
        expected = identity_document_hash(
            build_identity_document(
                schema=PROVIDER_CALL_CONFIG_SCHEMA,
                schema_version=PROVIDER_CALL_CONFIG_SCHEMA_VERSION,
                payload=config.identity_payload(),
            )
        )
        assert config.identity_hash == expected

    def test_config_hash_is_deterministic(self) -> None:
        first = openai_chat_config(
            model="m", controls=GenerationControls(temperature=0.2)
        )
        second = openai_chat_config(
            model="m", controls=GenerationControls(temperature=0.2)
        )
        assert first.identity_hash == second.identity_hash


class TestDefinitionVersusConfig:
    def test_definition_identity_differs_from_config_identity(self) -> None:
        definition = _fixed_definition()
        config = definition.materialize(
            controls=GenerationControls(token_limit=64)
        )
        assert definition.identity_payload() != config.identity_payload()
        # the Definition declares required variables; the Config assigns
        # them, so the assigned controls appear only in Config identity.
        assert "controls" not in definition.identity_payload()
        assert "controls" in config.identity_payload()

    def test_config_embeds_definition_identity_hash(self) -> None:
        definition = _fixed_definition()
        config = definition.materialize(
            controls=GenerationControls(token_limit=64)
        )
        payload = config.identity_payload()
        assert payload["definition_identity_hash"] == definition.identity_hash

    def test_config_identity_reflects_definition_variables(self) -> None:
        # Two definitions differing only in declared extension keys or
        # required controls yield different Config identities even with an
        # identical assignment, because the Config embeds the Definition
        # Identity Hash (which covers those declarations).
        base = _fixed_definition().materialize(
            controls=GenerationControls(token_limit=64)
        )
        with_extension_key = ProviderCallDefinition(
            definition_id="openai.chat_completions",
            route=ModelRoute(
                provider=ProviderKind.OPENAI,
                protocol=Protocol.CHAT_COMPLETIONS,
                model="m",
            ),
            constraints=ControlConstraints(
                token_limit_parameter=(
                    TokenLimitParameter.MAX_COMPLETION_TOKENS
                ),
            ),
            required_controls=frozenset({RequestControl.TOKEN_LIMIT}),
            extension_keys=frozenset({"seed"}),
        ).materialize(controls=GenerationControls(token_limit=64))
        assert base.identity_hash != with_extension_key.identity_hash

    def test_config_carries_typed_definition_reference(self) -> None:
        config = _fixed_definition().materialize(
            controls=GenerationControls(token_limit=64)
        )
        assert isinstance(config, ProviderCallConfig)
        assert isinstance(config.definition, ProviderCallDefinition)


class TestOutputAffectingControlsAreIdentity:
    def test_each_control_changes_config_identity(self) -> None:
        base = openai_chat_config(model="m")
        variants = [
            GenerationControls(temperature=0.5),
            GenerationControls(top_p=0.5),
            GenerationControls(token_limit=32),
            GenerationControls(reasoning=ReasoningEffort.LOW),
        ]
        hashes = {base.identity_hash}
        for controls in variants:
            hashes.add(
                openai_chat_config(model="m", controls=controls).identity_hash
            )
        # base plus four distinct control assignments = five identities.
        assert len(hashes) == 5

    def test_body_extension_changes_config_identity(self) -> None:
        base = openai_chat_config(model="m")
        extended = openai_chat_config(
            model="m",
            extensions=ProviderBodyExtensions(extra_body={"seed": 7}),
        )
        assert base.identity_hash != extended.identity_hash

    def test_model_route_changes_config_identity(self) -> None:
        a = openai_chat_config(model="m")
        b = openai_chat_config(model="other")
        assert a.identity_hash != b.identity_hash


class TestPolicyExclusion:
    """Transport policy fields must not appear in Config/Request identity."""

    def test_no_policy_keys_in_config_or_request_identity(self) -> None:
        config = openai_chat_config(
            model="m", controls=GenerationControls(token_limit=64)
        )
        request = ProviderCallRequest(config=config, transcript=TRANSCRIPT)
        policy = ProviderTransportPolicy(
            api_key_env=str(ApiKeyEnv.OPENAI),
            base_url=str(ProviderBaseUrl.OPENAI),
            timeout_seconds=5.0,
            idle_timeout_seconds=3.0,
            native_retry_count=3,
        )
        policy_keys = set(policy.identity_payload())
        config_text = str(config.identity_payload())
        request_text = str(request.identity_payload())
        for key in policy_keys:
            assert key not in config_text
            assert key not in request_text
        # positive: policy carries its own independent identity.
        assert policy.identity_payload()

    def test_request_fields_are_exactly_identity_bearing(self) -> None:
        # ProviderCallRequest holds only the two identity-bearing fields:
        # the Config reference and the Transcript. No transport policy or
        # copied controls sneak in as a field.
        assert set(ProviderCallRequest.model_fields) == {
            "config",
            "transcript",
        }

    def test_policy_identity_carries_no_credential_material(self) -> None:
        policy = ProviderTransportPolicy(
            api_key_env=str(ApiKeyEnv.OPENAI),
            base_url=str(ProviderBaseUrl.OPENAI),
        )
        payload = policy.identity_payload()
        # only the env var NAME, never a key value.
        assert payload["api_key_env"] == "OPENAI_API_KEY"
        assert "api_key" not in payload


class TestRequestIdentity:
    def test_request_identity_is_config_ref_plus_transcript(self) -> None:
        config = openai_chat_config(
            model="m", controls=GenerationControls(token_limit=64)
        )
        request = ProviderCallRequest(config=config, transcript=TRANSCRIPT)
        payload = request.identity_payload()
        assert set(payload) == {"config_identity_hash", "transcript"}
        assert payload["config_identity_hash"] == config.identity_hash
        assert payload["transcript"] == [{"role": "user", "content": "hi"}]

    def test_request_identity_copies_no_controls(self) -> None:
        config = openai_chat_config(
            model="m",
            controls=GenerationControls(temperature=0.9, token_limit=64),
        )
        request = ProviderCallRequest(config=config, transcript=TRANSCRIPT)
        payload = request.identity_payload()
        # controls live behind the Config reference, never copied onto
        # the request identity.
        assert "temperature" not in str(payload)
        assert "token_limit" not in payload

    def test_request_hash_changes_with_transcript(self) -> None:
        config = openai_chat_config(model="m")
        a = ProviderCallRequest(config=config, transcript=TRANSCRIPT)
        b = ProviderCallRequest(
            config=config,
            transcript=Transcript(
                messages=(
                    PromptMessage(role=MessageRole.USER, content="other"),
                )
            ),
        )
        assert a.identity_hash != b.identity_hash

    def test_request_hash_changes_with_config(self) -> None:
        transcript = TRANSCRIPT
        a = ProviderCallRequest(
            config=openai_chat_config(model="m"), transcript=transcript
        )
        b = ProviderCallRequest(
            config=openai_chat_config(model="other"), transcript=transcript
        )
        assert a.identity_hash != b.identity_hash


class TestPolicyFor:
    def test_derives_defaults_from_provider_kind(self) -> None:
        policy = policy_for(ProviderKind.ANTHROPIC)
        assert policy.api_key_env == ApiKeyEnv.ANTHROPIC.value
        assert policy.base_url == ProviderBaseUrl.ANTHROPIC.value

    def test_overrides_apply(self) -> None:
        policy = policy_for(
            ProviderKind.OPENAI,
            base_url="https://proxy.example/v1",
            api_key_env="CUSTOM_KEY_ENV",
            native_retry_count=2,
        )
        assert policy.base_url == "https://proxy.example/v1"
        assert policy.api_key_env == "CUSTOM_KEY_ENV"
        assert policy.native_retry_count == 2

    def test_idle_timeout_clamped_to_timeout(self) -> None:
        policy = policy_for(
            ProviderKind.OPENAI,
            timeout_seconds=10.0,
            idle_timeout_seconds=45.0,
        )
        # The idle timeout is the primary stall detector but can never fire
        # after the absolute cap; it is clamped down rather than rejected.
        assert policy.idle_timeout_seconds == 10.0

    @pytest.mark.parametrize(
        "timeout_seconds",
        [0.0, -1.0, float("nan"), float("inf"), float("-inf")],
        ids=("zero", "negative", "nan", "positive-inf", "negative-inf"),
    )
    def test_invalid_timeout_rejected(self, timeout_seconds: float) -> None:
        with pytest.raises(ValidationError):
            policy_for(
                ProviderKind.OPENAI,
                timeout_seconds=timeout_seconds,
            )

    @pytest.mark.parametrize(
        "idle_timeout_seconds",
        [0.0, -1.0, float("nan"), float("inf"), float("-inf")],
        ids=("zero", "negative", "nan", "positive-inf", "negative-inf"),
    )
    def test_invalid_idle_timeout_rejected(
        self, idle_timeout_seconds: float
    ) -> None:
        with pytest.raises(ValidationError):
            policy_for(
                ProviderKind.OPENAI,
                idle_timeout_seconds=idle_timeout_seconds,
            )

    @pytest.mark.parametrize(
        "native_retry_count", [-1, True], ids=("negative", "bool")
    )
    def test_invalid_native_retry_count_rejected(
        self, native_retry_count: int
    ) -> None:
        with pytest.raises(ValidationError):
            policy_for(
                ProviderKind.OPENAI,
                native_retry_count=native_retry_count,
            )

    @pytest.mark.parametrize("timeout_seconds", [1.0, 1e300])
    def test_positive_finite_timeouts_accepted(
        self, timeout_seconds: float
    ) -> None:
        policy = policy_for(
            ProviderKind.OPENAI,
            timeout_seconds=timeout_seconds,
            idle_timeout_seconds=timeout_seconds,
        )
        assert policy.timeout_seconds == timeout_seconds
        assert policy.idle_timeout_seconds == timeout_seconds


class TestRequiredVariableCompletion:
    def test_missing_required_control_rejected(self) -> None:
        definition = _fixed_definition()
        with pytest.raises(ControlValidationError) as exc_info:
            definition.materialize(controls=GenerationControls())
        assert exc_info.value.failure.code == "missing_required_control"

    def test_complete_assignment_produces_config(self) -> None:
        config = _fixed_definition().materialize(
            controls=GenerationControls(token_limit=64)
        )
        assert isinstance(config, ProviderCallConfig)
        assert config.controls.token_limit == 64


if __name__ == "__main__":  # pragma: no cover -- golden-hash regeneration
    print("GOLDEN_DEFINITION_HASH =", _fixed_definition().identity_hash)
    print("GOLDEN_CONFIG_HASH =", _fixed_config().identity_hash)
    print("GOLDEN_REQUEST_HASH =", _fixed_request().identity_hash)
